import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";
import { inter } from "@/app/fonts";
import { unstable_setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider, useMessages } from "next-intl"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ['en', 'ar'];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {

  unstable_setRequestLocale(locale);
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={cn("overflow-x-hidden", inter.className)}>
        <NextIntlClientProvider messages={messages}>
          <Navbar language={locale} />
          {children}
          <Footer language={locale} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
